### ISSUE TITLE
Question: Target OS

### ISSUE THREAD

**Issue by rudijs** [chainlayer/quicksync-playbooks#1]
Hi,

Quick question, what is the "ideal" target OS ?

Amazon Linux? Ubuntu?

Thanks!

**Comment by tyrion70** [comment]
Very sorry for the late reply, somehow I didn't get notified of open issues and PR's. Target OS should be any Linux distro supported by the chain, afaik thats most distro's like Ubuntu, Debian, Redhat, Suse and Amazon linux as well.
